//
//  MetricView.h
//  WallDisplayMapController
//
//  Created by Jialiang Xiang on 2016-03-17.
//  Copyright © 2016 Jialiang. All rights reserved.
//

#import <UIKit/UIKit.h>
#import "MetricsConfigs.h"

@class DataPointView;
@class MetricValueLabelView;

@interface MetricView : UIView
@property (readonly)DataPointView* dataPointView;

/**
 this view is not added to metric view itself, but is generated by it and added by the cell on top of it so that the metric views can be rasterized and cached
 */
@property MetricValueLabelView* metricValueLabelView;

/**
 @brief init with neither of the left or right line. Can be called multiple times to rewirte previous settings
 @param m the metric name must match the one in the dictionary
 @param p position must range from 0 to 1
 @warning does not call designated initializer
 */
- (id)initWithMetricName:(MetricName)m rawValue:(CGFloat)rv position:(CGFloat)p;

- (void)removeLeftLine;

- (void)removeRightLine;

- (void)addLeftLineWithPrevDataPointHeight:(CGFloat)h absHorizontalDistance:(CGFloat)d;

- (void)addRightLineWithNextDataPointHeight:(CGFloat)h absHorizontalDistance:(CGFloat)d;

// use notification center to send the message to show icons system wise in order to avoid complex passing mechanism
- (void) showIcons;

- (void)deactivateOldConstraintsAndActivateNewOnes:(NSArray<NSLayoutConstraint*>*) mvc;

@end
